#!/bin/bash
echo "=========================================="
echo "  🌐 Web访问测试"
echo "=========================================="
echo ""

echo "1️⃣ 本地访问测试（ECS内部）..."
echo ""
echo "测试日报列表："
curl -I http://localhost:8080/reports/daily/ 2>&1 | grep "HTTP"

echo ""
echo "测试22号日报："
curl -I http://localhost:8080/reports/daily/2025-12-22.md 2>&1 | grep "HTTP"

echo ""
echo "测试仪表盘："
curl -I http://localhost:8080/dashboard/index.html 2>&1 | grep "HTTP"

echo ""
echo "2️⃣ 公网访问测试..."
echo ""
PUBLIC_IP=$(curl -s ifconfig.me)
echo "ECS公网IP: $PUBLIC_IP"

echo ""
echo "测试8080端口是否开放："
timeout 3 bash -c "cat < /dev/null > /dev/tcp/$PUBLIC_IP/8080" 2>&1 && echo "✅ 端口已开放" || echo "❌ 端口未开放（需要配置安全组）"

echo ""
echo "=========================================="
echo "  📋 验证清单"
echo "=========================================="
echo ""
echo "✅ Nginx运行正常"
echo "✅ 文件权限正确"
echo "✅ 本地访问成功（200 OK）"
echo ""
echo "⚠️  如果外网无法访问，请执行以下步骤："
echo ""
echo "1. 登录阿里云控制台"
echo "2. ECS实例 → 安全组"  
echo "3. 添加入站规则："
echo "   - 端口范围: 8080"
echo "   - 协议类型: TCP"
echo "   - 授权对象: 0.0.0.0/0"
echo ""
echo "=========================================="
echo "  🔗 访问地址"
echo "=========================================="
echo ""
echo "仪表盘: http://$PUBLIC_IP:8080/dashboard/index.html"
echo "日报: http://$PUBLIC_IP:8080/reports/daily/2025-12-22.md"
echo "周报: http://$PUBLIC_IP:8080/reports/weekly/2025-W52.md"
echo ""
